-- Demo content for Business Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001, 0002, 0003, 0004).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.services, public.projects, public.resume_items,
  public.skills, public.testimonials, public.clients, public.pricing_plans, public.blog_posts, public.awards,
  public.stats, public.process_steps;

insert into public.site_settings (website_name, logo_url, accent_color, accent_color_2, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections) values
  ('Adrian Vale', null, '#4f3cf0', '#14d4f0', 'light', 'hello@adrianvale.demo', '+44 20 7946 0000', 'Adrian Vale — Web Developer & Business Growth Partner', 'Adrian Vale builds fast websites, brands and marketing that help small businesses and startups win more customers online.', 'Web developer and digital strategist helping small businesses grow online since 2018.', 'Let''s Talk', '[]'::jsonb);

insert into public.profile (full_name, professional_title, hero_headline, typed_roles, short_intro, bio, email, phone, location, profile_image_url, hero_image_url, hero_background_url, resume_url, availability_status, trust_line, about_title, about_image_url, about_points, experience_years, work_photos, social_links, skill_tools) values
  ('Adrian Vale', 'Business Growth Partner', 'I Help Businesses', array['Grow Online', 'Win More Clients', 'Rank on Google', 'Sell Online']::text[], 'Websites, branding and digital marketing for small businesses and startups. One partner from strategy to launch, focused on real results.', 'I''m Adrian Vale, a web developer and digital strategist. For 8 years I have helped local shops, agencies and startups turn their ideas into websites that bring customers.', 'hello@adrianvale.demo', '+44 20 7946 0000', 'London, United Kingdom', '/demo/avatar-owner.svg', '/demo/hero-portrait.svg', null, null, 'Available for new projects', '120+ businesses trust my work', 'Strategy, Design & Code — All in One Place', '/demo/about-portrait.svg', array['Idea Validation', 'Business Strategy', 'Online Business', 'Market Research']::text[], 8, '["/demo/work-meeting.svg","/demo/work-desk.svg","/demo/work-team.svg"]'::jsonb, '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"linkedin","url":"https://linkedin.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"x","url":"https://x.com/"}]'::jsonb, '[{"name":"Next.js","icon":"nextjs"},{"name":"Figma","icon":"figma"},{"name":"WordPress","icon":"wordpress"}]'::jsonb);

insert into public.services (title, short_description, icon_key, active, sort_order) values
  ('Website Development', 'Fast, SEO-ready business websites you can update yourself from a simple dashboard.', 'monitor', true, 1),
  ('SEO & Digital Marketing', 'Get found on Google, run smart ads and turn visitors into paying customers.', 'chart', true, 2),
  ('Brand Identity', 'Logo, colours and a brand voice that make your business look professional everywhere.', 'palette', true, 3),
  ('E-commerce Store', 'Online shops with secure payments, inventory and order tracking built in.', 'cart', true, 4),
  ('UI/UX Design', 'Clear, modern interfaces for web apps and dashboards your users enjoy.', 'layers', true, 5),
  ('Care & Maintenance', 'Updates, backups and security monitoring so your website keeps running smoothly.', 'shield', true, 6);

insert into public.projects (title, slug, category, year, client, role, intro, challenge, solution, result, cover_image_url, gallery, live_url, likes, featured, status, sort_order) values
  ('LearnHub Online Academy', 'learnhub-online-academy', 'Websites', 2026, 'LearnHub', 'Strategy, Design & Development', 'A course website and student portal for an online academy with 5,000+ learners.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-learnhub.svg', '["/demo/project-learnhub.svg","/demo/project-ledgerly.svg"]'::jsonb, 'https://example.com', 320, true, 'published', 1),
  ('Aurora Boutique Store', 'aurora-boutique-store', 'E-commerce', 2026, 'Aurora Boutique', 'E-commerce Design & Build', 'A fashion storefront with quick checkout, wishlists and a monthly lookbook.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-aurora.svg', '["/demo/project-aurora.svg","/demo/project-brewly.svg"]'::jsonb, 'https://example.com', 410, true, 'published', 2),
  ('Ledgerly Finance Dashboard', 'ledgerly-finance-dashboard', 'Web Apps', 2025, 'Ledgerly', 'UI/UX Design, Front-end', 'An invoicing and cash-flow dashboard for freelancers and small teams.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-ledgerly.svg', '["/demo/project-ledgerly.svg","/demo/project-learnhub.svg"]'::jsonb, null, 280, true, 'published', 3),
  ('Brewly Coffee Rebrand', 'brewly-coffee-rebrand', 'Branding', 2025, 'Brewly', 'Brand Identity', 'A warm, friendly identity and packaging system for a growing chain of coffee shops.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-brewly.svg', '["/demo/project-brewly.svg","/demo/project-aurora.svg"]'::jsonb, null, 350, true, 'published', 4),
  ('MediCare Clinic Growth', 'medicare-clinic-growth', 'Marketing', 2024, 'MediCare Clinic', 'SEO & Google Ads', 'Local SEO and ad campaigns that filled a dental clinic''s calendar within 90 days.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-medicare.svg', '["/demo/project-medicare.svg","/demo/project-propnest.svg"]'::jsonb, 'https://example.com', 190, false, 'published', 5),
  ('PropNest Real Estate', 'propnest-real-estate', 'Websites', 2024, 'PropNest', 'Design & Development', 'A property listing website with smart search filters and lead capture forms.', 'The business was getting traffic but very few enquiries. The old website was slow on mobile, hard to update and did not explain clearly why customers should choose them.', 'We started with a short discovery workshop, rewrote the key messages, and designed a fast, mobile-first website with clear calls to action. A simple dashboard lets the team update content without a developer.', 'Page speed improved to 95+, and enquiries more than doubled in the first three months. The team now publishes new offers and articles every week on their own.', '/demo/project-propnest.svg', '["/demo/project-propnest.svg","/demo/project-medicare.svg"]'::jsonb, null, 260, false, 'published', 6);

insert into public.resume_items (type, title, subtitle, period, badge, description, active, sort_order) values
  ('experience', 'Independent Web Developer & Strategist', 'Freelance — Worldwide', '2021 – Present', 'Remote', 'Helping small businesses and startups plan, build and grow their online presence.', true, 1),
  ('experience', 'Senior Front-end Developer', 'Brightpath Digital, London', '2019 – 2021', 'Full-time', 'Built websites and web apps for clients in retail, health and education. Led the agency''s performance and SEO work.', true, 2),
  ('experience', 'Web Designer', 'Northwind Agency, London', '2018 – 2019', 'Full-time', 'Designed landing pages, email campaigns and brand assets for local businesses.', true, 3),
  ('education', 'BSc in Computer Science', 'University of Greenwich', '2014 – 2017', 'First Class', 'Focused on web technologies, databases and human–computer interaction.', true, 1),
  ('education', 'Google Digital Marketing Certificate', 'Google Career Certificates', '2020', 'Certificate', 'SEO, search ads, analytics and conversion optimisation.', true, 2);

insert into public.skills (name, category, level, active, sort_order) values
  ('Web Development', 'Core', 96, true, 1),
  ('SEO & Marketing', 'Core', 88, true, 2),
  ('Brand Strategy', 'Core', 76, true, 3);

insert into public.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Sarah Mitchell', 'Owner', 'Bloom Dental Clinic', 'Website & Local SEO', 'Our old website brought zero leads. Adrian rebuilt it in three weeks and now we get new customer calls every single day.', '/demo/avatar-1.svg', 5, true, 1),
  ('Daniel Kim', 'Founder', 'Ledgerly', 'Finance Dashboard', 'Clear process, honest advice and a product our users love. Adrian felt like part of our team from day one.', '/demo/avatar-2.svg', 5, true, 2),
  ('Laura Reyes', 'Marketing Director', 'Aurora Boutique', 'E-commerce Store', 'Online sales grew 40% in the first quarter after launch. The store is fast, beautiful and so easy for us to manage.', '/demo/avatar-3.svg', 5, true, 3);

insert into public.clients (name, category, logo_url, website_url, active, sort_order) values
  ('Northwind', 'Brand', '/demo/logo-northwind.svg', null, true, 1),
  ('Lumen', 'Brand', '/demo/logo-lumen.svg', null, true, 2),
  ('Arcadia', 'Brand', '/demo/logo-arcadia.svg', null, true, 3),
  ('Kinetic', 'Brand', '/demo/logo-kinetic.svg', null, true, 4),
  ('Novaco', 'Brand', '/demo/logo-novaco.svg', null, true, 5),
  ('Orbit', 'Brand', '/demo/logo-orbit.svg', null, true, 6);

insert into public.awards (title, organization, year, short_description, image_url, link_url, active, sort_order) values
  ('Top Rated Plus Freelancer', 'Upwork', '2026', 'Awarded to the top 3% of freelancers for consistent five-star client feedback and on-time delivery.', '/demo/award-1.svg', null, true, 1),
  ('Best Small Business Website', 'UK Web Awards', '2025', 'Winner for the Bloom Dental Clinic website, recognised for clarity, speed and local SEO results.', '/demo/award-2.svg', null, true, 2),
  ('Google Partner Certification', 'Google', '2025', 'Certified in search advertising and measurement for running effective campaigns for clients.', '/demo/award-3.svg', null, true, 3);

insert into public.pricing_plans (name, tagline, price, period, description, features, cta_label, highlighted, active, sort_order) values
  ('Starter', 'Launch fast', '$990', 'one-time', 'A professional one-page website to put your business online quickly.', array['1 responsive page', 'Contact form & WhatsApp button', 'Basic SEO setup', 'Google Business setup', '7-day delivery']::text[], 'Get Started', false, true, 1),
  ('Business', 'Best value', '$2,400', 'one-time', 'A complete business website with blog, dashboard and on-page SEO.', array['Up to 8 pages', 'Admin dashboard', 'Blog & SEO setup', 'Speed optimisation', 'Analytics & reports', '30 days free support']::text[], 'Get Started', true, true, 2),
  ('Growth', 'Website + marketing', '$690', 'per month', 'Ongoing SEO, ads and content to keep new customers coming every month.', array['Monthly SEO work', 'Google & Meta ads', '2 blog posts per month', 'Monthly report call', 'Priority support']::text[], 'Get Started', false, true, 3);

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('7 Simple SEO Fixes Every Small Business Should Do', 'simple-seo-fixes-small-business', 'You don''t need an agency to start ranking. These seven fixes take an afternoon and make a real difference.', 'Most small business websites lose customers on Google because of a few simple, fixable problems.

## 1. Claim your Google Business Profile
It is free, and it is the first thing people see when they search for a local business.

## 2. One clear page per service
Google ranks pages, not websites. Give every main service its own page with a clear title.

## 3. Make it fast on mobile
Most visitors use a phone. Compress images and remove heavy plugins.

## 4. Write real titles and descriptions
Every page needs a unique title and a short description that makes people want to click.

## 5. Ask for reviews
Reviews build trust and help local rankings. Ask every happy customer.

## 6. Add your address and phone everywhere
Keep your name, address and phone number the same on every website.

## 7. Publish helpful articles
Answer the questions customers ask you every week. Each answer is a new way to be found.', '/demo/blog-seo.svg', 'SEO', '5 min read', '2026-09-12', 'published'),
  ('Why Your Website Loses Customers in 3 Seconds', 'why-website-loses-customers', 'Speed, clarity and trust decide whether a visitor stays or leaves. Here is how to fix all three.', 'Visitors decide in a few seconds whether your website is worth their time.

## Speed
If a page takes more than three seconds to load, many people simply leave. Optimise images and use modern hosting.

## Clarity
Your headline should say exactly what you do and who it is for. Clever slogans confuse people.

## Trust
Show real photos, reviews, client logos and clear contact details. People buy from businesses they trust.

- Test your site on a phone
- Read your headline out loud
- Ask a friend what you sell after five seconds', '/demo/blog-speed.svg', 'Web Design', '4 min read', '2026-08-28', 'published'),
  ('Social Media vs Website: Where Should You Invest?', 'social-media-vs-website', 'Social media brings attention, your website brings sales. How to make both work together.', 'Many businesses start on social media — and that is fine. But you do not own your followers.

## Social media is rented land
Algorithms change and reach drops. A post that reached thousands last year may reach a few hundred today.

## Your website is your shop
It works 24/7, shows up on Google and turns visitors into enquiries and sales.

## Use both together
Share useful content on social media and always point people back to your website to book, buy or contact you.', '/demo/blog-social.svg', 'Marketing', '3 min read', '2026-08-02', 'published');

insert into public.stats (value, label, placement, percent, active, sort_order) values
  ('95%', 'Client retention', 'about', 95, true, 1),
  ('3x', 'Avg. lead growth', 'about', 72, true, 2),
  ('120+', 'Projects delivered', 'band', 0, true, 3),
  ('85+', 'Happy clients', 'band', 0, true, 4),
  ('12', 'Countries served', 'band', 0, true, 5),
  ('4.9', 'Average rating', 'band', 0, true, 6);

insert into public.process_steps (title, description, active, sort_order) values
  ('Discover', 'A free call to understand your business, customers and goals.', true, 1),
  ('Plan', 'A clear proposal with scope, timeline and a fixed price.', true, 2),
  ('Build', 'Design and development with weekly progress updates.', true, 3),
  ('Grow', 'Launch, then SEO and support to keep results coming.', true, 4);

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Adrian Vale' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
